language: cpp

sudo: required
dist: trusty

env:
  - PACKAGES=libqt4-dev libqt4-private-dev
  - PACKAGES=qt5base-dev qtbase5-private-dev

compiler:
  - gcc
  - clang

branches:
  only:
    - master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq -y install $PACKAGES
  - git submodule update --init --recursive

script:
  - ./build.sh
