language: cpp

compiler:
  - gcc
  - clang

branches:
  only:
    - master

before_install:
  - git submodule update --init --recursive

sudo: false

addons:
  apt:
    packages:
    - libqt4-dev
    - libqt4-private-dev

script:
  - ./build.sh
